window.THOMAS_ASSIGNMENT = {
  id: 'THO-SSAT-TRIAL-VERBAL-HM01',
  endpoint: 'https://script.google.com/macros/s/AKfycbzF6aQZPpbL34Of--5r8zRZGI8Av2e8zTp11D_w820I9fNzLEAyY_YtvzLZ0-OVPFFw/exec',
  items: [
    { id: 'syn-01', section: 'Synonym', prompt: 'RESILIENT:', options: ['hardy', 'brittle', 'rigid', 'ordinary', 'hidden'] },
    { id: 'syn-02', section: 'Synonym', prompt: 'CONCISE:', options: ['exact', 'brief', 'cautious', 'smooth', 'complete'] },
    { id: 'syn-03', section: 'Synonym', prompt: 'DIMINISH:', options: ['reveal', 'postpone', 'reduce', 'gather', 'praise'] },
    { id: 'syn-04', section: 'Synonym', prompt: 'VIGILANT:', options: ['silent', 'flexible', 'ordinary', 'watchful', 'careless'] },
    { id: 'syn-05', section: 'Synonym', prompt: 'TRANQUIL:', options: ['crowded', 'risky', 'sudden', 'exact', 'calm'] },
    { id: 'syn-06', section: 'Synonym', prompt: 'IMPARTIAL:', options: ['fair', 'secret', 'energetic', 'loyal', 'doubtful'] },
    { id: 'syn-07', section: 'Synonym', prompt: 'OBSCURE:', options: ['famous', 'unclear', 'familiar', 'sturdy', 'generous'] },
    { id: 'syn-08', section: 'Synonym', prompt: 'AMPLE:', options: ['narrow', 'delayed', 'plentiful', 'accurate', 'useful'] },
    { id: 'syn-09', section: 'Synonym', prompt: 'FRUGAL:', options: ['cheerful', 'stubborn', 'wasteful', 'economical', 'exact'] },
    { id: 'syn-10', section: 'Synonym', prompt: 'TEDIOUS:', options: ['dangerous', 'skillful', 'gentle', 'brief', 'tiresome'] },
    { id: 'syn-11', section: 'Synonym', prompt: 'CANDID:', options: ['honest', 'noisy', 'polished', 'cautious', 'ordinary'] },
    { id: 'syn-12', section: 'Synonym', prompt: 'ELUSIVE:', options: ['harmless', 'difficult to grasp', 'eager', 'complete', 'shallow'] },
    { id: 'syn-13', section: 'Synonym', prompt: 'METICULOUS:', options: ['flexible', 'impatient', 'careful', 'generous', 'hidden'] },
    { id: 'syn-14', section: 'Synonym', prompt: 'MITIGATE:', options: ['predict', 'combine', 'reject', 'lessen', 'demand'] },
    { id: 'syn-15', section: 'Synonym', prompt: 'AMBIVALENT:', options: ['grateful', 'certain', 'careless', 'furious', 'conflicted'] },
    { id: 'ana-01', section: 'Analogy', prompt: 'Apprentice is to expert as', options: ['novice is to veteran', 'child is to toy', 'student is to book', 'worker is to wage', 'captain is to ship'] },
    { id: 'ana-02', section: 'Analogy', prompt: 'Compass is to direction as', options: ['map is to road', 'scale is to weight', 'clock is to calendar', 'ruler is to wood', 'telescope is to star'] },
    { id: 'ana-03', section: 'Analogy', prompt: 'Oasis is to desert as', options: ['rain is to cloud', 'ship is to harbor', 'island is to ocean', 'beach is to sand', 'tree is to forest'] },
    { id: 'ana-04', section: 'Analogy', prompt: 'Bark is to tree as', options: ['leaf is to branch', 'paint is to wall', 'roof is to house', 'skin is to animal', 'core is to fruit'] },
    { id: 'ana-05', section: 'Analogy', prompt: 'Antidote is to poison as', options: ['recipe is to meal', 'warning is to danger', 'shield is to armor', 'doctor is to patient', 'remedy is to illness'] },
    { id: 'ana-06', section: 'Analogy', prompt: 'Whisper is to speech as', options: ['drizzle is to rain', 'storm is to cloud', 'silence is to sound', 'letter is to word', 'song is to music'] },
    { id: 'ana-07', section: 'Analogy', prompt: 'Opaque is to transparent as', options: ['rough is to jagged', 'scarce is to abundant', 'quiet is to silent', 'narrow is to thin', 'cold is to winter'] },
    { id: 'ana-08', section: 'Analogy', prompt: 'Rehearsal is to performance as', options: ['ticket is to audience', 'stage is to actor', 'draft is to publication', 'chapter is to book', 'review is to critic'] },
    { id: 'ana-09', section: 'Analogy', prompt: 'Sculptor is to chisel as', options: ['author is to novel', 'pilot is to airport', 'teacher is to student', 'surgeon is to scalpel', 'farmer is to harvest'] },
    { id: 'ana-10', section: 'Analogy', prompt: 'Kennel is to dog as', options: ['leash is to dog', 'cage is to zoo', 'barn is to hay', 'pasture is to grass', 'stable is to horse'] },
    { id: 'ana-11', section: 'Analogy', prompt: 'Stanza is to poem as', options: ['scene is to play', 'cover is to book', 'shelf is to library', 'actor is to theater', 'word is to sentence'] },
    { id: 'ana-12', section: 'Analogy', prompt: 'Bud is to flower as', options: ['seed is to soil', 'larva is to butterfly', 'leaf is to tree', 'rain is to river', 'feather is to bird'] },
    { id: 'ana-13', section: 'Analogy', prompt: 'Cautious is to reckless as', options: ['silent is to quiet', 'angry is to furious', 'modest is to boastful', 'tired is to sleepy', 'rapid is to swift'] },
    { id: 'ana-14', section: 'Analogy', prompt: 'Map is to navigation as', options: ['road is to travel', 'compass is to north', 'kitchen is to meal', 'recipe is to cooking', 'book is to author'] },
    { id: 'ana-15', section: 'Analogy', prompt: 'Audible is to hear as', options: ['bright is to shine', 'soft is to touch', 'fragrant is to flower', 'loud is to sound', 'visible is to see'] }
  ]
};
