window.THOMAS_ASSIGNMENT={id:'THO-SSAT-C01-READING-HM01',endpoint:'https://script.google.com/macros/s/AKfycbzF6aQZPpbL34Of--5r8zRZGI8Av2e8zTp11D_w820I9fNzLEAyY_YtvzLZ0-OVPFFw/exec',items:[
{id:'read-01',section:'Main Idea',prompt:'Which statement best expresses the main idea of the passage?',options:['A successful project excuses a temporary violation of a safety rule.','Taking responsibility includes admitting a poor choice, repairing what can be repaired, and accepting what cannot be undone.','Competition usually prevents students from making careful decisions.','Honesty matters only when an accident causes physical injury.','A well-designed model is more important than the process used to present it.']},
{id:'read-02',section:'Text Structure',prompt:'The safety notice in the first paragraph mainly serves to',options:['explain why the pump stopped working.','show that the exhibit rules were confusing.','prove that Leon had previously caused an accident.','establish the clear standard that Mira later chooses to ignore.','suggest that the judges preferred projects beside a wall.']},
{id:'read-03',section:'Vocabulary in Context',prompt:'In the second paragraph, “rationalize” most nearly means',options:['invent reasons that make a poor choice seem acceptable.','calculate how much time a repair will require.','explain a scientific process in simple language.','change a plan after considering new evidence.','criticize another person for breaking a rule.']},
{id:'read-04',section:'Character Motivation',prompt:'Why does Mira agree to hide the cord beneath the mat?',options:['She believes the teacher has quietly approved Leon\'s idea.','She wants to prevent nearby teams from seeing the pump.','She assumes the younger students will avoid the aisle.','She hopes the judges will reward the repaired riverbank.','She wants to protect the team\'s chance in the first round without spending time moving the display.']},
{id:'read-05',section:'Inference',prompt:'The passage suggests that moving the display beside the wall was',options:['impossible because no outlet was available there.','a safer option that Mira rejected because it required time and rebuilding.','forbidden by the exhibit judges.','likely to damage the projects of nearby teams.','Leon\'s original plan before the pump failed.']},
{id:'read-06',section:'Cause and Effect',prompt:'Which event is the widest repercussion of Mira\'s shortcut?',options:['The edge of the mat rises above the floor.','Mira briefly considers blaming the mat.','Leon suggests hiding the cord.','Nearby teams must move their projects away from the spill.','The pump stops moving water through the model.']},
{id:'read-07',section:'Figurative Language',prompt:'The phrase “honesty cannot rewind” emphasizes that',options:['Mira cannot remember the exact order of events.','the judges refuse to listen to Mira\'s explanation.','telling the truth cannot remove every result of an earlier choice.','the repaired model is less accurate than the original.','the final round begins before Mira can finish speaking.']},
{id:'read-08',section:'Tone',prompt:'The tone shifts from the second paragraph to the final paragraph from',options:['urgent and self-justifying to sober and reflective.','cheerful and playful to angry and accusing.','confused and doubtful to humorous and relaxed.','formal and scientific to mysterious and fearful.','hopeful and admiring to sarcastic and critical.']},
{id:'read-09',section:'Character Evidence',prompt:'Which action most clearly demonstrates Mira\'s integrity?',options:['She helps design a flood-safe neighborhood.','She notices that the mat appears flat.','She wants the model to reach the first judging round.','She looks at the repaired paper street.','She gives the teacher a complete account of the shortcut and helps repair the damage.']},
{id:'read-10',section:"Author's Purpose",prompt:'The final paragraph mainly serves to',options:['introduce a new conflict between Mira and the judges.','distinguish improving later actions from erasing earlier consequences.','prove that the team would have won the first-round prize.','explain how the flood-safe model operates.','show that Leon alone was responsible for the shortcut.']}
]};
