window.THOMAS_ASSIGNMENT={id:'THO-SSAT-C07-READING-HM01',endpoint:'https://script.google.com/macros/s/AKfycbzF6aQZPpbL34Of--5r8zRZGI8Av2e8zTp11D_w820I9fNzLEAyY_YtvzLZ0-OVPFFw/exec',items:[
{id:'read-01',section:'Reading · Main Idea',prompt:'Which statement best expresses the main idea of the passage?',options:['British leaders rejected colonial demands because they wished to prevent alliances with foreign powers.','The Declaration was written mainly to list every complaint the colonists had made since 1763.','Colonial resistance broadened from seeking correction within the empire to publicly explaining independence.','Armed conflict created immediate agreement among colonists that separation was the only possible course.','The most reliable way to understand the Revolution is to memorize its dates and laws.']},
{id:'read-02',section:'Reading · Specific Detail',prompt:'According to the first paragraph, boycotts and petitions were at first intended to',options:['persuade foreign governments to provide military assistance.','establish independent governments in every colony.','force Parliament to end all forms of taxation.','unite colonists behind an immediate declaration of independence.','ask British leaders to correct particular grievances.']},
{id:'read-03',section:'Reading · Supported Inference',prompt:'The statement that colonial opinion “remained divided” suggests that',options:['the delegates had stopped organizing collective responses.','fighting persuaded most colonists to return to full support of British authority.','armed conflict did not produce immediate or universal support for complete separation.','colonists disagreed mainly about whether the Stamp Act had existed.','reconciliation had already become impossible by 1774.']},
{id:'read-04',section:'Reading · Vocabulary in Context',prompt:'As used in the third paragraph, “rests on” most nearly means',options:['is protected from.','is based on.','is delayed by.','is separated from.','is enforced through.']},
{id:'read-05',section:'Reading · Cause and Effect',prompt:'According to the passage, what most directly made complete separation a more believable course of action?',options:["Parliament's need for revenue after a costly war",'Delegates meeting to organize a collective response',"The Declaration's appeal to audiences beyond North America",'Failed petitions and widening armed conflict','The power of independent states to form alliances']},
{id:'read-06',section:'Reading · Paragraph Purpose',prompt:'The second paragraph primarily serves to',options:['trace escalating resistance as separation became more plausible despite divided loyalties.','explain why the Stamp Act raised more money than Britain expected.','describe the exact military outcome of the battles at Lexington and Concord.','prove that colonists agreed on independence before any fighting began.','outline the four sections of the Declaration.']},
{id:'read-07',section:'Reading · Cross-paragraph Relationship',prompt:'Which choice best describes the relationship between the boycotts and petitions in the first paragraph and the Declaration in the third paragraph?',options:['Both were chiefly attempts to persuade foreign nations to aid the colonies.','The petitions presented the final political resolution that Congress later repeated unchanged.','The Declaration returned to the same limited goal of correcting particular grievances.','The earlier actions sought reform within the empire; the Declaration justified separation.','The earlier actions responded to the Declaration by challenging its principles.']},
{id:'read-08',section:'Reading · Reference',prompt:'In the third paragraph, the phrase “those principles” refers to',options:['the military strategies used at Lexington and Concord.','the broad ideas about legitimate government, including consent of the governed.','the particular taxes Parliament imposed after 1763.','the powers of independent states to form alliances and govern themselves.','the demands made by foreign audiences outside North America.']},
{id:'read-09',section:'Reading · Textual Evidence',prompt:'The statement that the Declaration addressed “audiences beyond North America” supports which conclusion?',options:['Its writers expected every foreign nation to enter the conflict.','The document was meant chiefly for people who could not read English.','Congress believed colonial supporters no longer needed persuasion.','The king was not among the document\'s intended audiences.','The document sought effects outside the colonies as well as within them.']},
{id:'read-10',section:'Reading · Tone',prompt:'The tone of the passage is best described as',options:['outraged and accusatory.','celebratory and patriotic.','measured and explanatory.','doubtful and apologetic.','humorous and dismissive.']}
]};
