window.THOMAS_ASSIGNMENT={id:'THO-SSAT-C05-READING-HM01',endpoint:'https://script.google.com/macros/s/AKfycbzF6aQZPpbL34Of--5r8zRZGI8Av2e8zTp11D_w820I9fNzLEAyY_YtvzLZ0-OVPFFw/exec',items:[
{id:'read-01',section:'Main Idea',prompt:'Which statement best expresses the main idea of the passage?',options:['A community can create belonging by taking distinct histories seriously without erasing them.','Newcomers can succeed only by hiding their customs until they understand local routines.','School projects are most effective when they focus on one shared national history.','Family objects matter more than relationships formed in a new community.','Migration always leads to permanent isolation.']},
{id:'read-02',section:'Detail',prompt:"According to the first paragraph, what contributed most directly to Mina's sense of displacement?",options:['Adults described the move as an opportunity.','Her grandmother\'s cloth was embroidered with waves.','Her cousins lived in several countries.','The move separated her from familiar routines and relatives.','The schoolhouse in Harbor City was crowded.']},
{id:'read-03',section:'Inference',prompt:"Which inference about Mina's classmates before the map project is best supported by the passage?",options:['They intentionally tried to force Mina to leave the school.','Their ordinary habits could make a newcomer feel excluded even without open hostility.','They knew nothing about their own family histories.','They disapproved of every custom from outside Harbor City.','Mr. Chen required them to speak rapidly.']},
{id:'read-04',section:'Vocabulary in Context',prompt:'As used in the second paragraph, “peripheral” most nearly means',options:['geographically remote.','financially costly.','unimportant or outside the main concern.','incomplete but promising.','closely connected.']},
{id:'read-05',section:'Paragraph Purpose',prompt:'The third paragraph primarily serves to',options:['explain why Mina decides to return to Aru.','prove that all the students share the same history.','compare the practical value of a map and a recipe.','provide a factual overview of immigration to Harbor City.','introduce an activity that turns separate histories into a basis for connection.']},
{id:'read-06',section:'Concept Comparison',prompt:"Which statement best describes the passage's distinction between “integrate” and “assimilate”?",options:['To integrate is to forget the past, while to assimilate is to protect it.','The two words describe exactly the same process.','To integrate concerns physical location, while to assimilate concerns school routines.','To integrate is to participate in a group, while to assimilate may mean that visible differences fade.','A person must assimilate completely before beginning to integrate.']},
{id:'read-07',section:'Symbol and Evidence',prompt:'The blue cloth is significant mainly because it',options:["links Mina's heritage to a contribution she can share with the class.","shows that Mina's past prevents her from adjusting to school.","proves that Mina's family was wealthy before moving.",'reveals that blue is a common color in Harbor City.',"replaces Mina's need to form relationships with classmates."]},
{id:'read-08',section:'Structure',prompt:'Which choice best describes the structure of the passage?',options:['It gives steamship details and then presents a history of mapmaking.','It establishes displacement and alienation, introduces a communal response, and traces individual and group change.','It presents two opposing arguments about whether Mina should leave Harbor City.','It lists vocabulary terms and then adds an unrelated school example.',"It compares Mina's school with diaspora communities in several countries."]},
{id:'read-09',section:'Tone Shift',prompt:"Mina's experience moves primarily from a tone of",options:['anger to sarcasm.','formality to humor.','uneasiness and isolation to cautious hope and inclusion.','nostalgia to regret.','indifference to fear.']},
{id:'read-10',section:'Title',prompt:'The title “The Map in the Hall” is most significant because it',options:["shows that the hall is the school's largest physical space.","emphasizes the geographic accuracy of the students' routes.",'suggests that the students compete to see who traveled farthest.','names the actual display and symbolizes how distinct routes can meet in a shared community.','proves that a map can remove cultural differences.']}
]};
