window.THOMAS_ASSIGNMENT={id:'THO-SSAT-C01-VERBAL-HM01',endpoint:'https://script.google.com/macros/s/AKfycbzF6aQZPpbL34Of--5r8zRZGI8Av2e8zTp11D_w820I9fNzLEAyY_YtvzLZ0-OVPFFw/exec',items:[
{id:'syn-01',section:'Synonym',prompt:'JUDICIOUS:',options:['wise','hasty','silent','rigid','ordinary']},
{id:'syn-02',section:'Synonym',prompt:'CULPABLE:',options:['careful','uncertain','powerful','blameworthy','forgiving']},
{id:'syn-03',section:'Synonym',prompt:'CONCEAL:',options:['explain','examine','hide','repair','divide']},
{id:'syn-04',section:'Synonym',prompt:'NEGLIGENT:',options:['patient','careless','honest','alert','grateful']},
{id:'syn-05',section:'Synonym',prompt:'RECTIFY:',options:['predict','delay','correct','discuss','measure']},
{id:'syn-06',section:'Synonym',prompt:'ACCOUNTABLE:',options:['cautious','secretive','powerful','responsible','guilty']},
{id:'syn-07',section:'Synonym',prompt:'IMPULSIVE:',options:['steady','rash','formal','distant','exact']},
{id:'syn-08',section:'Synonym',prompt:'DISREGARD:',options:['ignore','admire','record','approach','repeat']},
{id:'syn-09',section:'Synonym',prompt:'INTEGRITY:',options:['speed','ambition','obedience','talent','honesty']},
{id:'syn-10',section:'Synonym',prompt:'MITIGATE:',options:['expose','lessen','combine','refuse','predict']},
{id:'syn-11',section:'Synonym',prompt:'PRUDENT:',options:['cautious','restless','stubborn','generous','gloomy']},
{id:'syn-12',section:'Synonym',prompt:'FORESEEABLE:',options:['fortunate','immediate','predictable','avoidable','harmful']},
{id:'syn-13',section:'Synonym',prompt:'RATIONALIZE:',options:['remember','condemn','conceal','justify','correct']},
{id:'syn-14',section:'Synonym',prompt:'REMORSE:',options:['anger','regret','confusion','relief','doubt']},
{id:'syn-15',section:'Synonym',prompt:'FORTHRIGHT:',options:['cautious','impartial','flexible','reserved','candid']},
{id:'ana-01',section:'Analogy',prompt:'Prudent is to reckless as',options:['quiet is to silent','cautious is to rash','angry is to furious','rapid is to swift','tired is to sleepy']},
{id:'ana-02',section:'Analogy',prompt:'Remorse is to wrongdoing as',options:['pride is to effort','courage is to danger','relief is to sleep','grief is to loss','curiosity is to study']},
{id:'ana-03',section:'Analogy',prompt:'Warning is to danger as',options:['map is to road','question is to answer','symptom is to illness','rule is to judge','shelter is to storm']},
{id:'ana-04',section:'Analogy',prompt:'Conceal is to reveal as',options:['withhold is to disclose','gather is to collect','delay is to postpone','reduce is to lessen','repair is to restore']},
{id:'ana-05',section:'Analogy',prompt:'Rectify is to error as',options:['predict is to result','avoid is to choice','measure is to length','explain is to question','heal is to wound']},
{id:'ana-06',section:'Analogy',prompt:'Incentive is to action as',options:['wheel is to vehicle','author is to book','fuel is to motion','shelter is to animal','clock is to time']},
{id:'ana-07',section:'Analogy',prompt:'Rule is to conduct as',options:['judge is to verdict','compass is to direction','school is to student','lock is to key','artist is to canvas']},
{id:'ana-08',section:'Analogy',prompt:'Negligence is to accident as',options:['exercise is to strength','practice is to skill','medicine is to recovery','drought is to crop failure','map is to navigation']},
{id:'ana-09',section:'Analogy',prompt:'Accountable is to action as',options:['liable is to debt','visible is to color','fragile is to glass','eager is to contest','silent is to speech']},
{id:'ana-10',section:'Analogy',prompt:'Judge is to verdict as',options:['author is to library','pilot is to runway','teacher is to lesson','referee is to ruling','doctor is to medicine']},
{id:'ana-11',section:'Analogy',prompt:'Admit is to fault as',options:['conceal is to secret','confess is to wrongdoing','predict is to result','repair is to object','avoid is to danger']},
{id:'ana-12',section:'Analogy',prompt:'Integrity is to deception as',options:['silence is to noise','speed is to motion','patience is to waiting','skill is to practice','courage is to cowardice']},
{id:'ana-13',section:'Analogy',prompt:'Mitigate is to harm as',options:['notice is to detail','create is to plan','soften is to impact','argue is to claim','measure is to distance']},
{id:'ana-14',section:'Analogy',prompt:'Deliberation is to decision as',options:['rehearsal is to performance','actor is to stage','chapter is to book','tool is to worker','audience is to applause']},
{id:'ana-15',section:'Analogy',prompt:'Foreseeable is to predict as',options:['flexible is to bend','fragile is to break','pleasant is to enjoy','audible is to hear','honest is to trust']}
]};
